
input-jti:
  image: $INPUT_JTI_IMAGE_NAME:$IMAGE_TAG
  container_name: $INPUT_JTI_CONTAINER_NAME
  environment:
   - "INFLUXDB_ADDR=opennti"
   - "OUTPUT_INFLUXDB=true"
   - "OUTPUT_STDOUT=false"
   - "OUTPUT_KAFKA=true"
   - "KAFKA_ADDR=localhost"
   - "KAFKA_PORT=9092"
   - "KAFKA_TOPIC=jnpr.jvision"
  ports:
   - "$LOCAL_PORT_JTI:50000/udp"
   - "$LOCAL_PORT_ANALYTICSD:50020/udp"
  links:
    - opennti

input-oc:
#  image: $INPUT_OC_IMAGE_NAME:$IMAGE_TAG
  build: $INPUT_OC_DIR
  container_name: $INPUT_OC_CONTAINER_NAME
  volumes:
    - ./$INPUT_OC_DIR/start-input-oc.sh:/source/start-input-oc.sh
    - ./$INPUT_OC_DIR/telegraf.tmpl:/source/telegraf.tmpl
  ports:
    - "$LOCAL_PORT_OC:50051/udp"
  links:
    - opennti

input-internal:
#  image: $INPUT_INTERNAL_IMAGE_NAME:$IMAGE_TAG
  build: $INPUT_INTERNAL_DIR
  container_name: $INPUT_INTERNAL_CONTAINER_NAME
  environment:
    - "HOST_PROC=/rootfs/proc"
    - "HOST_SYS=/rootfs/sys"
    - "HOST_ETC=/rootfs/etc"
  volumes:
#    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys:/rootfs/sys:ro
    - /proc:/rootfs/proc:ro
    - /etc:/rootfs/etc:ro
  links:
    - opennti
    
opennti:
  image: $MAIN_IMAGE_NAME:$IMAGE_TAG
  container_name: $MAIN_CONTAINER_NAME
# Uncomment environment to allow anonymous grafana access
# and disable user sign up
#  environment:
#   - "GF_USERS_ALLOW_SIGN_UP=false"
#   - "GF_AUTH_ANONYMOUS_ENABLED=true"
  volumes:
   - ./$LOCAL_DIR_DASHBOARD:/src/dashboards
   - ./$LOCAL_DIR_DATA:/opt/open-nti/data
  ports:
   - "$LOCAL_PORT_STATSD:8125/udp"
   - "$LOCAL_PORT_NGINX:80"
   - "$LOCAL_PORT_GRAFANA:3000"
   - "$LOCAL_PORT_INFLUXDB:8083"
   - "$LOCAL_PORT_INFLUXDB_API:8086"
